baseURL = "https://www.mockingbirdconsulting.co.uk/"
languageCode = "en-gb"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
#[[menu.main]]
#name    = "About"
#url     = "about"
#weight  = 2
[[menu.main]]
name    = "Kits"
url     = "kits"
weight  = 2
[[menu.main]]
name    = "Rural Broadband"
url     = "rural-broadband"
weight  = 3
[[menu.main]]
name    = "Kits"
url     = "kits"
weight  = 2
[[menu.main]]
name    = "Portfolio"
url     = "portfolio"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Connecting you with your environment"
author = "Mockingbird Consulting Ltd"
# Google Analitycs
googleAnalitycsID = "UA-98611453-1"
fb_app_id = "1301301486613337"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io
siteName = "Mockingbird Consulting"
title = "Connecting you with your environment"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/header-bg.jpg"
heading = "CONNECTING YOU WITH YOUR"
description = "Complete connectivity solutions, from broadband and networks to environmental and agricultural monitoring"
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# Custom 404 settings
[params.banner404]
enable  = true
bgImage = "images/header-bg.jpg"
heading = "Page not found"
description = "We're sorry we couldn't find what you were looking for."
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "FARM"
[[params.banner.flipText]]
title   = "SHOP"
[[params.banner.flipText]]
title   = "OFFICE"
[[params.banner.flipText]]
title   = "FACTORY"
[[params.banner.flipText]]
title   = "ENVIRONMENT"

# Homepage About Section
[params.about]
enable  = true
title   = "Efficient, stable, cost-effective solutions for your estates and premises"
content = "Frustrated by your broadband speeds? Suffering from patchy WiFi in your office or on your farm? Need to know more about soil conditions, vehicle & asset locations, customer behaviour or air quality?<br /><br />Mockingbird Consulting can help.<br /><br />We have solutions for all the above and much more, allowing us to provide you with one phone number to call and a single support contract covering everything from broadband connectivity into your site through to knowing the temperature of your fridges and freezers."
image   = "images/about.png"

# Call to Action
[params.cta]
enable  = true
title   = "WANT TO KNOW MORE?"
content = "Get a free, no-commitment 30-minute consultation for your farm, office, factory, or shop"
btnText = "Let's go!"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Projects and Blog Posts"
subtitle= "From Farming to Factories and Offices to Shops, find out what we've been up to recently and get inspiration from our blog posts and analysis"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/MockingbirdConsultingLtd/"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/mockingbirdconsulting/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/company/mockingbird-consulting"
