baseURL = "https://www.mockingbirdconsulting.co.uk/"
languageCode = "en-gb"
title = "Connecting you with your environment | Mockingbird Consulting"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Service"
url     = "service"
weight  = 3
[[menu.main]]
name    = "Gallery"
url     = "gallery"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Connecting you with your environment"
author = "Mockingbird Consulting Ltd"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/header-bg.jpg"
heading = "CONNECTING YOU WITH YOUR"
description = "OUR SOLUTIONS FOR MONITORING THE WORLD IN WHICH YOU LIVE AND WORK ARE PROVEN TO ENHANCE THE WAY YOU INTERACT WITH YOUR ENVIRONMENT"
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "FARM"
[[params.banner.flipText]]
title   = "SHOP"
[[params.banner.flipText]]
title   = "OFFICE"
[[params.banner.flipText]]
title   = "FACTORY"
[[params.banner.flipText]]
title   = "ENVIRONMENT"

# Homepage About Section
[params.about]
enable  = true
title   = "KNOW MORE. MAKE BETTER DECISIONS."
content = "The more you know about the environment around you, the more effectively you can manage it.<br /><br />Whether you're looking to keep track of your livestock and heavy plant on a farm or building site, want insights into how your customers feel about your business, or just want to ensure that meeting rooms are being used as effectively as possible - Mockingbird Consulting have a solution for you."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "WANT TO KNOW MORE?"
content = "Arrange a free 30 minute consultation with one of our team so we can help you get started"
btnText = "Book Now!"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Projects and Sensors"
subtitle= "From Farming to Factories and Offices to Shops, find out what we've been up to recently and get inspiration from our blog posts and analysis"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/MockingbirdConsultingLtd/"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/mockingbirdconsulting/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/company/mockingbird-consulting"
