baseURL = "//www.mockingbirdconsulting.co.uk"
languageCode = "en-gb"
title = "Complete Farm Management from Mockingbird Consulting"
theme = "infinity-hugo"
relativeurls = true

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"

[params]
    description    = "Live updates on security, livestock movement, soil conditions, water levels, and much more delivered direct to you wherever you are."
    seo_tags = [ "farm management", "digital farm management", "IoT", "Agricultural IoT"]
    # Matomo Web Stats
    matomo_rootURL = "//webstats.mockingbirdconsulting.co.uk/"
    matomo_siteID = 1
    # Navigation
    [params.navigation]
        logo = "images/logo.png"
        home = "Home"
        about = "About"
        service = "Services"
        contact = "Contact"

    # Hero Area
    [params.hero]
        enable      = true
        bg          = "images/header-bg.jpg"
        title       = "FROM FIELD TO FARMER"
        subtitle    = "Live updates on security, livestock movement, soil conditions, water levels, and much more delivered direct to you wherever you are."
        btnText     = "Learn more"

    # About Section
    [params.about]
        enable      = true
        heading       = "Take control of your farm with a fully managed solution from Mockingbird Consulting."
        description = "Tell us about your farm and we'll provide you with everything you need to understand at a glance what is happening on your estate.<br /><br />Sensors, connectivity, and a management dashboard are all included for one low monthly fee."

        [[params.about.sliderItem]]
            image   = "images/about/1.jpg"
            description = ""
    
    # Service Section
    [params.service]
        enable      = true
        title     = "We focus on the technology, so you can focus on the farming"
        subtitle    = "Even for the smallest farm, new & affordable technology can help you can make even better decisions about the way you manage your business on a day to day basis. Get immediate alerts to critical incidents - all through your mobile phone, tablet or PC no matter whether you are on, or off, your farm."
        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-lock2"
            title   = "Secure your premises"
            description = "Get alerts when gates or barn doors open at unusual times or are left open by people passing through your land. Track the location of expensive machinery and livestock and find out if they leave your land unexpectedly."
            delay   = "0s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-map2"
            title   = "Monitor your field and crop activity"
            description = "Virtually \"walk the farm\" by receiving updates through your phone on what is happening in the growth cycles of your valuable crops, livestock, woodlands, and fields so you can respond immediately to problems."
            delay   = "0.2s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-linegraph"
            title   = "Monitor your environment"
            description = "Keep an eye on air temperature, humidity, and soil & water quality to evaluate the environment and microclimates across your land. Get alerts to your phone for particular environmental situations that could damage your business."
            delay   = "0.4s"

    
        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-puzzle"
            title   = "Start small, grow big"
            description = "We know not all farms are the same, so our starter packs are designed to grow with you. Add new types of sensor or just increase the number of existing ones, it's all compatible with the platform."
            delay   = "0.4s"

    
    
    # Call to Action Section
    [params.cta]
        enable      = true
        bg          = "images/call-to-action.jpg"
        title       = "Get early access"
        subtitle    = "Fill in your details below, and you could get early access to the platform as part of our beta programme."

    [params.contact]
        enable      = true
        title       = "Get In Touch"
        subtitle    = "Do you have a question that isn't answered here? Fill in the form below and we'll find you an answer!"

