# A basic redirect rule
[[redirects]]
  from = "/case-studies/*"
  to = "/portfolio/:splat"

# Set CORS
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[context.deploy-preview]
    HUGO_VERSION = "0.69.2"
    command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
HUGO_VERSION = "0.69.2"
command =  "hugo  --enableGitInfo --minify  --buildFuture --ignoreCache -b $DEPLOY_PRIME_URL"
